version: '3.1'

services:

  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: example

  wiki:
    image: 2eeb9a92d2b9
    restart: always
    environment:
      DATABASE_VAR: DATABASE_URL
      DATABASE_URL: postgres://dhyrdcvppxhdtp:3a85f05a441da8e6aed7b5c250894a0643f14a35974f27e324e4657134f88590@ec2-3-222-150-253.compute-1.amazonaws.com:5432/d40k6lrns2v7ck
      PORT: 8080
    ports:
      - 8080:8080
